after_success:
- git checkout .validate.json
- "./node_modules/.bin/grunt coveralls"
before_script:
- "./node_modules/.bin/bower install"
env:
  global:
  - secure: IbEByPgIgAu1gGfalHjHyoY+t2HvaCns/X7khKIY883urRFayKzj06V4Mdz6vjTgxe3+/p7SHhSyGQFlGZp6AjxolGKB3mMKy0+fdfMa2kJgXoW2pSAKBoEwDFvmUbdsi1dDCsbbkrNOJo7kBEW3XbhyXG1qmoSZmEm3x3/Q5rNpQq/cxx2S9Ssy/Tz8k57Js3/aIer2hKoDBghLewkSbMzF/FqVJd3keyOkCN856j3q+Z7X6fivi6sjGIWkzoux+KS3ip3aptLhaddkDnNhCzeuISOiE4iZjCiwPVUg0ETqQaKJulDCm+hnXCqgCy2DpWR/jn86+8U6fTLfwf3trybS2yzjkf1IFRAv/3CkFvhNsJqtvxrfbVpNHrbUcKUQzBHSSU1Y1e3Eb/ubv7zeBRA/paXhMsC5jcUEPSNQ3maxioha7+DOOydb4BL5nzxlG4StQh6T2oWiEvGA//BZnVWSBb8C0HRvOHiDCC16t1FlRWnnA3mss5e4JzoEA8e3b0sSaxb0Bq6Q9cumQHoFHwNjwkDIOoZvprYQpc33HGq0pHOaVoXHKvTY3w4ap2Tob9JMRgBYQezRmwYqskX9h1SDLydCSb7WWzEeZIcvQtITddL+0fg+de3/K1G+R8/WMZDlMdN7cTFnKuN85T+Kc11h+PjQWTbx++4gMIk/Ixo=
  - secure: IFgw6/BeP5tbVvfltvtPRqrV6c7eDrJYP9T9sFIoIthqhSP0sgZQ/k2Qr3B+226dXd2kLn3Xt2c8DLyjA1b9SAdqQw/0+hetbheP9PwSCgHrggP/hS+8MjAdg7Mw/8498xck5v3IE5f2UQAz91XwWrCTnwFd1yBRaC1GMpi198fZM/X2fZYL5CsxNfdRzVWbKglSGzETeSXgHet+KMfB8Sy1CfKAEjhKL7fHCUXcGzQ7Z0EPgqZhj+xSY8R1XAzYIHbS9fFbxCHBTaab9+v27juY57ZqrywVrA5yvuIdvB/I70JGaq7ZX3n7dbhDDQVdn5E9UktsL7HVxrHuQ5VWL9JgzhfEFcpp21y2ZXT6qi05XQGQ90NKivp0+cIQRKJ9iw4bWHz+7NBn/0co+EPvarDuvurl6J+9AG4B9ygnzGp7QtES5UYdUK0J/juUKmhJiGN2irpBdy3CfUP6koQWdidOJJmqF4oc47p2zWNyH9fPuvnZ78Ezz9F8r1dDLT/qpB6885VR4W46VxvOf8tz3+V8l+jt/9xnxA6QSAlPu0n8uakydd3z7UqVmFlXH8PWzFctgXNhDms13X3OYRt+/PjrvueqdT14df51rWDLJDHPuYEXsAdBAeXK81usak80y1tcvPnJw21rJMn89BAPt1F8qR1STlV8prdVEBcMtOg=
language: node_js
matrix:
  allow_failures:
  - node_js: '0.13'
node_js:
- iojs
- '0.13'
- '0.12'
- '0.10'
sudo: false
