after_success:
- git checkout .validate.json
- "./node_modules/.bin/grunt coveralls"
before_script:
- "./node_modules/.bin/bower install"
env:
  global:
  - secure: uLzID3stKqSXGjEy3qSAo65gVqgrD0lz+clLqjnMEG1t3nazIGbdKdpP8PHN9q6lrvrs3GNZnYIEY0DlxIeQWt1+DGScRC4V3DH3VHAZ4420vy4QJE+EtI045csPy+UfmUdir8A35JwaWRVpDB8c8HX5hEzkEcVOo/HZ2sb6vg/8NlYBMnsisoXtGoM3jiseQzIL1j5U3+5hm5H6RvmDt7CGfxpxdX/Yw4vbvDlj22jecW49zdHJZwiLOXaQXHdEjNYrsILlXrhIt/WnwT8m/sLJOlJSNroCY53ye9jcsF6Ktt3te+NAhG1tDBF6nrzsYaMDERiL1A6b3zKjj2UmbG07lnW7Xz95j5mKYFhEu57Vvw9707J8Do88xDWYsW8R+u89E36TH5xpVTcQ7Hvj88yqYBcFjrQw9zl3We51MlUxgVGT5ZHYOE7ByQ9OIcVPCObJfKNiOge2qw+hUpp6EB94EyEYDJ/V7l9U/3+KCz0EZPI7K+iTugJFUF3A/GgEHt+jBGb1c7bkmaRP7ci/+rr8HBUr207HJNNsE44LLwIMYrN3Z0gIO3OAiy4vRAVcHTO/I7WsfQTmCFN5bAVnklxA5IorFcsI65PVA70qZpoZU9mphL3NE5LOw5FEvFyIDVgCkOoJJe8V78Yvvbd1vvKP7fVapAQDt1JwDoHoIgU=
  - secure: K2W1AVeFOklTPjQkLTAkAXN4JWyuUYa9c1chyuiafecUctfzwC7uJ7ofR6vXyI9+2hrMDXUZTVOd/OkUSna4/xE7K5RDL4Ygyfs8c5AFq4/rLk9A64L0YVUGDXE8nIGaLPLvN0ES78ZSc0mbhuS+6G5IZ52bnyQ2BCbBumLZcygWa27QruyODgy+JO7doKZj75qm/DWDXrT+hSH+sHFqdtvGkKiCm1BxqpF1oXBB6jIobyZi7MU3qA4xttoNcKTgdfXW1cYd5TfY93BvxKOtIAAmDDh2FcM9m5A7iS94k17TcQcRWwxB2chsc5QZ05jMwwwZGX8lK2SMugtYgaRV131N+jahWhrZvktNRLa9BwDCVV8vR3reIzqFCH7BvmMpYw1AREGx++TJ8emtoeX4t4SfOPJWT2T+u2CEIVvJgmPYs7bcu43eXlkBTZi0nxzZSfJwMn2Fukw+j+TPoMUzeT0uWPPudhzGE04GabJbmuH757FDZiss+hwliGsWnkYQd8FrVTXr0zAOiWc7BXmSrorb3lMalsNtguIlb8biIUbYRRSasNTFvi9MiF4NCEruVq9ge29yUrB+vm5vixnHRT6WsUbRuSMa1Bge3U1qe6NHxxOlnQVDB/BhQChKDHPO1PVVhr2aQe6KPdYfSkF6yO2ikh+AOiFd5HH8teJbOdM=
language: node_js
matrix:
  allow_failures:
  - node_js: '0.13'
node_js:
- iojs
- '0.13'
- '0.12'
- '0.10'
sudo: false
