after_success:
- git checkout .validate.json
- "./node_modules/.bin/grunt coveralls"
before_script:
- "./node_modules/.bin/bower install"
env:
  global:
  - secure: KyUsASaBRs87I+2lgpn90cdDSrrAIqvld1Z2IFMy/z+y4gtGVe+fSV6S8h3g6QikHsC54/0ERd7d9tad5D4FtwYe6wojnlz8GGrUDf3Tw7UsaCQN7Nzr+dSr4zzRU5q7rreWkz9Sc691Kw9br4Tj3UaQUzQlmhJUqyFZyEF9S4X3Fhe9+0mLzlvTdmR9bYjhswRX3ERZcbEotpp8ZQDGhkk/omT6TZP13Rjp0nLoalyfphYVzNV7Hq91wyWK2+MTb60to5xmM3DhECHRcekhKRnGmuaa+6zXGwfXtofSRsDcycUHT99PiTu1LTvWJR4oYkZDk2k2XZdLsPDY0PdraiMoGZ7ILJVNipQ6E9+kKDJiZe5BNXKrhSyysx2sCAETzd8/2lBiB1t3Nr/dKcjD3tTfaCtjVRqEov5KFm9oXHof9KaZugjGSquX7syjsMssWvqzHOYUo3rDvLWEcm2fXwIm2l0+nw7VSr4XlBRlSzTf44knaaCUsq8JfCjvy70dpv522RaMf7F2rtnIiqWvx5r2Vb97chVsv+B7APmgs/8eOrsb/NzHXPYOMZMuoyqtYw7Q+WcSwhjNaaALrdlu62ZKFMqMbFus/I98ZDpf6EklMNo7vyGVzLDvpXd2zh/XHb0i9CZmjKS8qsjvRPRwsJ6alrZTuy/jje3wZd5OJcA=
  - secure: mEiWUZuXTgE75aWCo4WGM7YzAjqs1sAl8dp3dHecfb8nLBu7a7dobTmbvQhLF6nqgRer01OOlTIiRmfqVgW85d7gKPZNtj+fjF0fe4Me6oFVQS7cLhi+MMhoCSnov7/0SDr+lnwv/FhGZExx942r9bp9zjHI2tFbkSnPQyBaLu7FSjfUQk5NFI3FanlQ7G5jux+gixQLbA6bWdRE4BMTgAP4v+nMtPkl+A8wfEYJgjGq6hmx0yy1tD2TzqIJELjs/yV4ihuEUzKyi/G5RFJPFGZC6/JkW3Xm6RpoBkEjDOItU8fDzhqcC5AW2WtoUYpW0JuEIKc7WSlhEQe/z01EeC+siqqA9LU/WBd+W3vD31ydSepiEfy6ePc+xpKdIndLLphORBChYg2Z9uz6TPcJnp2Z8lPneqiyeaH2E1JgiOPIvZdXRAqxdLOHvcwsg81BTW9Znw0j5+eiK80uAjGirJnhebsT4PXbVXevB1V5t0MAVebwR0bYENpKFmPLE/5h4jsbfnIYzC7Im0MZPrewdUoNM6Tj65gS5Api7AitJPj0/ERjF4zI9KRuCWS5pvOaeQ/9uBpPpPAwYbLISMEDz2nFVON4B9LgIO4KrEWuXER6KnSUJ3pvUXkOXNYJ/ZqH03S/TtvxT28b/uoyodNrQPXBeb2XX22HFhDCsXaCC0k=
language: node_js
matrix:
  allow_failures:
  - node_js: '0.13'
node_js:
- iojs
- '0.13'
- '0.12'
- '0.10'
sudo: false
