after_success:
- git checkout .validate.json
- "./node_modules/.bin/grunt coveralls"
before_script:
- "./node_modules/.bin/bower install"
env:
  global:
  - secure: diWYFuoRYEnWTsBdcBRraWTtVLAlbu14sPlTEboO4YXqhXbGYqY/BEPQRuZhC0avWR2yhFMDrolAFUPXHAnurOZ8D8dZbc6i0Ku0dNNKK6eIR2VrhGWN1kA6260N3QPiNn7gmiv199mEsiFJogc2u3QeFZD3j23ebJ9mrRjuZroCKDM/Mrr+CIR3mbSM2WarBXiWuWweB+pj3R4cR5HfxXdiwU7ZkxbQ4pYkcMIZbHkOoP2Y1Yo0lNaprJRH7zlnZhZb9EzaGydVuNp3S7k61Iab6Nzl6Exli7t7qNKqrWdWkzkBSbv1k7t7guYsdexYmxfWm8G73e8QOUQ170LMc2vq3F1PqWwcuayGY0gLgaV6OnBRgsMJegHhAekIE0cNOri50l1zv0NRAsNv/ug4hLFZ7LBL+QisGptGgkhnP22EAqHpBrulJT3n2h0hCLo08sniiVOUy1UlScjctZGBJ/eyHugI1WnWn+zpRJ2GJ7jtsBKPvHnBZ3XdfprxFnqRBlaUv/vIaykrDyvi38zZHc7HXYHGgSKWycjz56tLrA13v6KxCuLZh3FlR2Nz6jBBq07aMTsTq6hJAhiXXNmdI6clea/G2sp2SOeUnO+soLIuu7aygSGxgj3zv0/yysi019+tUWsQkZaO3lsYFwLHw6/Vg/FiDYOAn3vzX7BNYw8=
  - secure: F93VudQ/JQWnXOrsnwSbv60MQFqFa/s//+hyAcrrCb5XiAbNqZO44AkpjmwZv1Hp2TeH0eml/r9B7KWyyx3AawVKIjSfudrzvF/L7om7hSG+liRigtBK3znNEiPo7uh97cS90/zF7DN1Cm431okgnj6av1TfSuy7Aev0KgtgSK6CCh6QuAwAa4lAJDYnf+VAAdr0ETEQapIpCKlmUM8z1qE7RbdmA5nn1Wd/ZLchMmGYva2O+RPO0Mx2rcIPzzerS9EAct0qMWPIGksuoxPyGQ06J9Ghx6N6oB9B7QyQw47TNK/WznhjM9hzBgvfUhNT5mAszr3tb3fD1m7Wq92Bh/SxpurgfbTHGNJO6vOV1oGCB6Iz2BMDl5E+ePvOeRlzJpg6awjBeKnWmtiojCB3PrsGw+qEMPkYfi22qDDu4REXierzvLGASiJyVeje/t/NVP4QxksRun2OtPMjwNwbrUE914iG20/SGxREpaFqfWY4VHyWkUfwlg9M4WSrQatt1A2Acp1+HLB36eAjjyUVfvXiYqU1Lw3ILoIG9QIOy4Xbjow5a5gq1fIbVfjBT0PBl/EEULQOK3cGeklNgZIU6VNiCyJGi/Aw+i1rnru6C6oX8uwjWvymz+VtJcNtMs00fJslaP6MRFoy4YraCS+mUHRv26JP84ABC2iWQX7v52M=
language: node_js
matrix:
  allow_failures:
  - node_js: '0.13'
node_js:
- iojs
- '0.13'
- '0.12'
- '0.10'
sudo: false
