after_success:
- git checkout .validate.json
- "./node_modules/.bin/grunt coveralls"
before_script:
- "./node_modules/.bin/bower install"
env:
  global:
  - secure: uUpgtk/7i3HxQ/RfnY8oo0zicKiiUiSCFsP2iAFiX04pXeyy4FssuNkBT2zzyyjdg1qtPFNOCxsNOS8taDr0Dp7jtXl1BxrR464701SLmmKnv/fVc+56ufG03EJB4VMGSWi/316tetCdc2jy1MEUk4YkwfQq44aIF71qclTGxIGqONi7f06oZncx8/PiTHfKATxqbZPGSNBQe6IWUdvoljYzduQlzZGZn/YfoUwZcnK3/rod885lxgvEN1s4i/BSfZX7kiJQiVXUqiB11eDtebvA46EW8HwhOqmR1Na0uvZRVUSOnnKrJ6Nb4q6cp9kfFJ808WG0H4GcLegkFj5I64O+ZbV/ApUnAMDixF7IvZNelNpVZbBJjzNgwXMNZ/sGQmX/6vDQ+vsJjAqy307FrHBT6mSKvchbPoceA1X2hF6dwHMqNIYx1FS6uz7VGKO3bH034GcexP5f0Rdi0gFdKxh1CyU59ZPDwRaEibrmqiqROr7dAQcJHJUcApaohuIdD9J4eQ0ei2xn9D/jQ+zikHQX6hDH6+qE5bnHEC1IoFasA/zSiOHq65s8KZkgyY5qsE8EkJQ4dnI+uoMs56VQJuz5eLaOf3wumR0wXCsmCjhGRmbiCgPDg3V735FFwjG/hquu1tYUA+zFIBXbbGztD9zWeorYvxA1Yhv8ii+BvnY=
  - secure: ZoWIFHWd3FVUz2YnWZowzmoY13Y9HzMM1USN7kwvQmv5JszPLMdMLhb0Bu87/ahl9ZzDqf6ghANr5f+n7T1fgo1YFuu+jAWgUxe98nHET8hrl9Uq1U+89Cpz3VTHpbjinUOv7prfkba9BaqC74ZYM9k0sxPE5KM+ozEMLWZXOSCCdOXx6nNsmW+eimmJnPmRRTkGuQZKEzZW0/yKQOVUx3DslW6LVszlgHghD7dxzJmZ5IQH5EPEiZ3t63A2kTWBJxGgKzYNw2y1q6d4iYc6zuKRFfJlhavebKpIHXD4Kjhvl2vL0kIINNEgIiWBLEJB7qYuHoeq/yhlSu/vsA8NEQ+NwF3AQlfctyDSBnIURaHs5HWcnqRATJQejqatWcN72bZF/36kVYpJ1ajXRKfml2Q6dEAk4ROxwbgFSKMru191IoKlK1iYQBBVUprfiTFZjM3g9BEihx6xmR3d+unvT7PVJdJEEHuqrOtL1FmufCTUjcgjcqkrkR3FhqjAfp0HOWJUZ7UqvNT+Fmyjs2dELmYczAZJiFEscL8KYXt7hdIeRRY1n9LHEznrisAbI+VNPLlgsVzhbhcYbWKOY0R0vP0ry9NG3CIvzY/dP1Y5l6p4p2ASMe+i5ITnKCv6KtkAGRkOc4480iIeqM23+pRxTDWTVQbjBMJSQMzJdX/cTH8=
language: node_js
matrix:
  allow_failures:
  - node_js: '0.13'
node_js:
- iojs
- '0.13'
- '0.12'
- '0.10'
sudo: false
