after_success:
- git checkout .validate.json
- "./node_modules/.bin/grunt coveralls"
before_script:
- "./node_modules/.bin/bower install"
env:
  global:
  - secure: ny2KdPF9FdQDDLuGQ06DIWwYXuAKZ4LVXZe77Nwfek8dMFNabZFt+/lC1OU32LH4LQ2svPI1dErB+Hu/QK9WZGUv61QYmnXVqP9HFEfA0TInSXzRR6Fc8G5Jwtzw78NqDUUKo6KtBLjudndAEWhYzSjKb01PDW/W9+Mn8IJ/JqyBi09diTO1gcWlJq9HYCsRQoIZHr9tQ3tx9au4/ucjO4ggeQRzNFtvRB4J0mBdMWSMRtaW42GSaZim1ytzRGXRwHrBDcPSl61VrQu0RSzj9vNU+vFQDgz4TKCrMHlFoNdsP03Pnrxzs/vn/8jqj/TqYMzQe9zJAWgpdqH1WB3Dgxf0GWpfH43nplKkQKcXSiWfGkK2HXWRxdl98Vr25QzrCs5AZno5mCn5c1/tMrv571aZMVPABiv9R4UMbdPkcKmuWm26d1/XIWWkDJ7GhXq4Iv93U30tDtnzmhBL1iDoIihA59GIl4lDGvtrlewgVX6FtlABquorFv93bWqG3Y0EwRFm6rKZV/7LwLiuqATQjDReqW5rprOf3yY9HSvxLjOZ0RcQh/BmQ0lzcvI1p1eUvG8uD6Vi4lOMiWFO+biqW7O28PkEMQhQjVuoIFQFo8qhgQs5Vvk5L+HC1TlVWCJjjYzBHCdd+9tN+vK2JexLRDEd+vnc36u9UkEQUcRdyAY=
  - secure: KIPifCcuCi0Ezz9QX/Z/X712OhM3FW8T59VQvmgzNILUimfEBXQ+w5TkqJP4GJp8vVBnd+MNmFkcANV2U8FzwpSN5DbHodg+X+dloy1hI77QxsWUcZ/oIAZc7EdmY7aWpqtNtzR+f97o3oVxc49xawYBUvV3iR/ofXli2xq99WuGcg6i5D7J00d4928hMF8OJfkcdao9uxExGMPp7wcy8Y0BuuZKW4kq4Yh0BV7uhjtSOs8A0OuSGjOx4gyPabMZq33bsnS0kok3J+k8NUfRyUBK81QPghVltbH/+2IQaSRTHXXsGpMtCZKAgmScr5ipMOiIPjSEO4p7iGmA79jNNvNom1BmDzxhG7OAoksGepVt50rxF2aAh/6d+R0mx0BXXRjw5ah2DSnGhwkOlH3RGecllwhiGtyOEYuQ4lu0TRuJe6u5/sSFGZ6usJVUmOR8sr8hMgiNFx/3UgOxrU4DY7t9+B+tbuIi0bvkPClbQOW5W4zk76cJysw2Vg5KKTfDgSrlZOY75azY6iMbTLRVEs7nIEtjVJPDIv3ZS3zgOeMaTDqAzikwdvPCIgZ+D7oJ31cjuEEp3ZRMvcOG5o9u1wZfq0haKhHKLXB0sCRB1Il0ybrLOlDH9iFikqSeqnuk6thsUzqeSO8hJ/AXSNGCCTB/9qb9niT6QYRSdKqEuDg=
language: node_js
matrix:
  allow_failures:
  - node_js: '0.13'
node_js:
- iojs
- '0.13'
- '0.12'
- '0.10'
sudo: false
